package tm;

public enum ActionType {
    DISCARD,
    PLAY,
    PASS,
    ENERGY,
    TEMPERATURE,
    WATER,
    GREENERY,
    CITY,
    PLANT_TO_GREENERY,
    HEAT_TO_TEMPERATURE,
    TR,
    HEAT_TO_MONEY,
    CUSTOM,
    SEARCH_FOR_LIFE,
    INVENTORS_GUILD,
    MARTIAN_RAIL,
    WATER_IMPORT_FROM_EUROPA,
    SPACE_ELEVATOR,
    DEVELOPMENT_CENTER,
    EQUATORIAL_MAGNETIZER
}
